### ISSUE TITLE
SA-CADRL

### ISSUE THREAD

**Issue by Yuanzizizi** [mit-acl/rl_collision_avoidance#15]
Hi,

I am also interested in your work SA-CADRL (Socially Aware Motion Planning with Deep Reinforcement Learning). But I could not find this policy (SA-CADRL) under "gym-collision-avoidance/gym_collision_avoidance/envs/policies"

Could you please offer me some code to learn?

Thanks a lot~

**Comment by Yuanzizizi** [comment]
Plus, I have another detailed question for SA-CADRL.

Is the sub-goal the furthest point that the global path can be captured within the local map area?  
![image](https://user-images.githubusercontent.com/105049539/182111911-3a7b2af3-e5ee-419e-bc6b-01d32b59da37.png)

**Comment by mfe7** [comment]
The code in [this directory](https://github.com/mit-acl/gym-collision-avoidance/tree/release/gym_collision_avoidance/envs/policies/CADRL) contains original SA-CADRL code (despite the directory being named CADRL). The `'cadrl'` policy that agents are able to use in that gym environment should be SA-CADRL agents, but not trained with the social terms, by default. I believe you could specify a different pickle file somewhere in the agent initialization to instead use NN params that were trained with right-handed norms.

For the subgoal, there was no "global path" per se. We had a global goal, and we selected a subgoal from points along motion primitives (the blue/orange lines). The selection criteria was to minimize a distance to the global goal -- we tried using various distance metrics, including Euclidean distance and a diffusion distance given a prior floorplan of the building. There should be more detail about this in my master's thesis.
