### ISSUE TITLE
Cannot execute ./install.sh

### ISSUE THREAD

**Issue by nfhe** [mit-acl/rl_collision_avoidance#16]
Hello, thanks for sharing your awesome work. I'm a beginner about this field and this is the first time I learn about it. I have been troubled by the above questions for a long time. I hope you can help me, thank you very much!

**WhenI want to execute. / install.sh，I have a error!**

`(avoidance) he@he-Lenovo-Legion-R7000P2020H:~/drl-test/src/rl_collision_avoidance$ ./install.sh 

Python 3.6.9 :: Anaconda, Inc.
Your python version is: . Please replace it with Python 3.4-3.7 so we can use tensorflow 1.` 

Python=3.6.9,tensorflow=1.14.
I don't how to solve it.
Thank you very much!

**Comment by mfe7** [comment]
Have you tried running the install script outside of your anaconda environment? I personally don’t use anaconda, and the install script will create a virtual environment itself, so I suspect there would be some conflict between those two types of environments. If you need a specific version of Python, I use pyenv to manage multiple versions on my machine.

**Comment by nfhe** [comment]
Thank you for your reply. I have solved the last problem according to your reply. But now there is a new problem.

**When I execute. / install.sh，I have a error in /[gym-collision-avoidance](https://github.com/mit-acl/gym-collision-avoidance)/install.sh.!**

![1659848693(1)](https://user-images.githubusercontent.com/92715669/183276141-f51d31ae-ceb7-4622-ae50-8fec81182e47.png)

![1659849091(1)](https://user-images.githubusercontent.com/92715669/183276308-0c0741bb-2480-499c-8db0-f79aab16b72f.png)

I don't how to solve it.
I hope to get your reply.
Thank you very much!

**Comment by mfe7** [comment]
Hmm that seems like a pip install / git pull issue, unrelated to this repo. I haven't seen that one before.

**Comment by nfhe** [comment]
Thank you very much for your reply.

I have found an alternative. Let's talk about it in order to avoid such problems for the latecomers.

**python3 -m pip install git+https://gitee.com/he-naifeng/baselines.git**.

I want to close this comment. Thank you very much.
