### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by farhadvaseghi** [mit-acl/rl_collision_avoidance#17]
Hello, Mr. Everett
I have question, how do you normally debug the code like this when it starts running from a terminal as a bash shell script file ??
Do you use any specific tool? I tried to use a library named pdb but it doesn't work properly.

**Comment by mfe7** [comment]
I have used pdb with this -- one issue may be that the train script starts 32 parallel jobs by default, maybe it would be easier to debug a small piece if you change this down to 1 in the config.py file. Alternatively, the bash scripts just set some environment variables, source some other shell scripts/enter a virtualenv, and then run the python code, so you might be able to run these commands separately while debugging.
