### ISSUE TITLE
Question about how to make Learning cadrl!

### ISSUE THREAD

**Issue by kmzdaniel** [mit-acl/rl_collision_avoidance#19]
Hello, Mr. Everett.
I added an Extended on your last ga3c code and tested it.
and I need extra credit for my article. for that, I will be testing this Extended on your 'cadrl' model.
but I can't find a policy like the 'LearningPolicyGA3C.py', Is there any way to make it?

**Comment by mfe7** [comment]
Hi - I'm not sure I follow what you are asking.

**Comment by kmzdaniel** [comment]
Hello again - I need learning code of 'CADRL', like ['LearningPolicyGA3C.py'](https://github.com/mit-acl/gym-collision-avoidance/blob/5dda5a2a1e146a249130a18dbbb7271f1d2c6c31/gym_collision_avoidance/envs/policies/LearningPolicyGA3C.py).

**Comment by mfe7** [comment]
There is a pre-trained CADRL policy in the gym environment, same folder as the policy linked above.

If you are trying to train a new policy using the CADRL algorithm, we never put together a clean release of that training code.  All the training code should be buried somewhere deep in the gym environment as well, but I can't speak to how easy it would be to run that (it's quite old).

**Comment by kmzdaniel** [comment]
Many thanks for your adequate explanation.
