### ISSUE TITLE
How to train other datasets?

### ISSUE THREAD

**Issue by superjinger** [mit-acl/rl_collision_avoidance#2]
Hello, what should I do if I want to train with my own dataset?

**Comment by mfe7** [comment]
Hi, I'm not sure what you mean by your own dataset because this repo uses reinforcement learning through a simulator.

**Comment by superjinger** [comment]
> Hi, I'm not sure what you mean by your own dataset because this repo uses reinforcement learning through a simulator.

thank you for your reply,
My own dataset means that I use sensors to obtain a group of random walking positions of pedestrians, and  I want to use this dataset as the trajectory of obstacles. So do I need to retrain ga3c_cadrl with this dataset, or use ga3c_cadrl directly for testing?

**Comment by mfe7** [comment]
Oh cool, I see now. You could use ga3c_cadrl in a couple ways:

- if you're putting this on a robot or want to use ROS, there's a pre-trained ROS package available in our cadrl_ros repo. You can modify the code to accept your format of pedestrian positions (and it will output robot speed/heading commands)
- you could re-train a ga3c_cadrl policy using this repo if that pre-trained policy doesn't work well enough. But a fixed dataset of pedestrian trajectories can't be immediately plugged into training with this repo. If you want to do that, you might consider imitation learning instead. We have a basic regression script for initializing the network from a fixed dataset of (ped states, robot action) pairs but it won't give useful performance without RL.

**Comment by superjinger** [comment]
> Oh cool, I see now. You could use ga3c_cadrl in a couple ways:
> 
> * if you're putting this on a robot or want to use ROS, there's a pre-trained ROS package available in our cadrl_ros repo. You can modify the code to accept your format of pedestrian positions (and it will output robot speed/heading commands)
> * you could re-train a ga3c_cadrl policy using this repo if that pre-trained policy doesn't work well enough. But a fixed dataset of pedestrian trajectories can't be immediately plugged into training with this repo. If you want to do that, you might consider imitation learning instead. We have a basic regression script for initializing the network from a fixed dataset of (ped states, robot action) pairs but it won't give useful performance without RL.

Thank you very much, I will try the ways you provided !
