### ISSUE TITLE
Question about umber of episodes and fix one mistake in code!

### ISSUE THREAD

**Issue by kmzdaniel** [mit-acl/rl_collision_avoidance#20]
Hello, Mr. Everett.
in [line 356](https://github.com/mit-acl/gym-collision-avoidance/blob/5dda5a2a1e146a249130a18dbbb7271f1d2c6c31/gym_collision_avoidance/envs/collision_avoidance_env.py#L356), a negative(behind "dist_btwn_nearest_agent[i]/2.") must be turned into a positive.
and the question is:
should I use more episodes if I train GA3C in a "single agent" way? (For example, for phase one, over 1,500,000 to four agents.)

**Comment by mfe7** [comment]
Thanks for pointing this out. In terms of numbers of episodes, the best advice I can give is to experiment with different numbers and see at what point the reward curve seems to converge to a reasonable answer. I don't know of a more principled answer to specifying the number episodes a priori

**Comment by kmzdaniel** [comment]
Many Thank for your guidance.
