### ISSUE TITLE
Issue with downloading Regression dataset

### ISSUE THREAD

**Issue by SacheetA** [mit-acl/rl_collision_avoidance#22]
Hello, 

The regression datasets provided in the folder 'mit_acl/rl_cllision_avoidance/ga3c/GA3C/datasets' are not downloadable.
It would be really helpful if the issue is rectified soon.

Thanks, 
Sacheet Amblekar

**Comment by mfe7** [comment]
they should be stored in the repo using git lfs - did you try using git lfs to pull those and/or download them directly from this web interface?

**Comment by SacheetA** [comment]
The web interface for download doesn't seem to work. 'git lfs pull' seems to work. 
Thanks.

**Comment by SacheetA** [comment]
The dataset is named '2_3_4_agents_cadrl_dataset_action_value_train.p', but regression training code is for 2 agents (defined in config). Will it be a problem?

**Comment by mfe7** [comment]
i do not fully remember, but that number in the config is used in part to set up the network structure. so you may want to change that to be 4?

**Comment by SacheetA** [comment]
Yeah, some changes were required. I did the same and it works. Thanks for the response!
