### ISSUE TITLE
Test Cases in FullTestSuite

### ISSUE THREAD

**Issue by SacheetA** [mit-acl/rl_collision_avoidance#25]
Hello, how were the test cases generated in the full test suite? Is there a code for it?
Also, in the test cases folder, there is no test case file for 20 Agents, could you please upload it in the repo?

**Comment by mfe7** [comment]
To generate the full test suites, there is some example code at the end of the test_cases python script (but I don't have the exact settings on hand right now): https://github.com/mit-acl/gym-collision-avoidance/blob/903564097509e3fbdbbb850a3a89729a28377b81/gym_collision_avoidance/envs/test_cases.py#L1044

I don't think we have a 20-agent full test suite, but rather just had the 20-agent circle case specified in the test_cases python script.

**Comment by SacheetA** [comment]
Okay, thanks!
