### ISSUE TITLE
tensorflow/core/util/events_writer.cc:108] Write failed because file could not be opened.

### ISSUE THREAD

**Issue by BingHan0458** [mit-acl/rl_collision_avoidance#8]
Hello, I'm sorry about that I got an error again. The following results are got when I run `./train.sh TrainPhase1`
```
[Time:       73] [Episode:     2482 Score:    -0.3096] [RScore:     0.0788 RPPS:  3934] [PPS:  3818 TPS:    29] [NT:  2 NP:  2 NA: 32]
[Time:       74] [Episode:     2483 Score:    -0.2500] [RScore:     0.0776 RPPS:  3932] [PPS:  3817 TPS:    29] [NT:  2 NP:  2 NA: 32]
[Time:       74] [Episode:     2484 Score:    -0.4117] [RScore:     0.0762 RPPS:  3940] [PPS:  3816 TPS:    29] [NT:  2 NP:  2 NA: 32]
2021-03-25 22:01:55.812621: E tensorflow/core/util/events_writer.cc:108] Write failed because file could not be opened.
2021-03-25 22:01:55.812772: E tensorflow/core/util/events_writer.cc:108] Write failed because file could not be opened.
2021-03-25 22:01:55.812847: E tensorflow/core/util/events_writer.cc:108] Write failed because file could not be opened.
[Time:       74] [Episode:     2485 Score:    -0.3115] [RScore:     0.0764 RPPS:  3923] [PPS:  3810 TPS:    29] [NT:  2 NP:  2 NA: 32]
[Time:       74] [Episode:     2486 Score:    -0.3202] [RScore:     0.0760 RPPS:  3906] [PPS:  3810 TPS:    29] [NT:  2 NP:  2 NA: 32]
[Time:       74] [Episode:     2487 Score:     0.1893] [RScore:     0.0766 RPPS:  3914] [PPS:  3814 TPS:    29] [NT:  2 NP:  2 NA: 32]
```
How to deal with the bug about `tensorflow/core/util/events_writer.cc:108] Write failed because file could not be opened.`
Thank you very much!

**Comment by mfe7** [comment]
I haven't seen this one before. Seems like a tensorflow issue beyond my knowledge. Our script saves checkpoints at some regular interval -- maybe you could see what file it's trying to save and see if the directory's permissions are set up correctly?

**Comment by BingHan0458** [comment]
Thank you. I deal with it.
In fact, I want to try to base your code to deal with collision avoidance problems in 3D space with the point cloud data. Do you think it is feasible or hard to implement? Or do you have any recommended?
Looking forward to your suggestions。
Thank you very much!

**Comment by mfe7** [comment]
Cool.

Extending the code from 2D->3D would be doable. The main places that would need to be changed are: 
- a new `Agent` class where positions/goals/headings are extended to 3D
- a new 3D `Dynamics` superclass and new 3D `Policy` superclass
- new collision checking/reward methods in the environment (e.g. as a superclass of the current env)
- new testcases that initialize agents in 3D
- new visualization code

However, pointclouds seem beyond the scope of this repo. There is some simple code to ray-trace for 2D laserscans, but it's not well-tested nor efficient. If you wanted to try pointclouds and maintain the dynamics/policies of this repo, the way I would consider is to simultaneously run another simulator (e.g. gazebo, unity) that renders the pointclouds for you. This repo's environment could send the states of agents to gazebo/unity, and gazebo/unity could send back the agents' sensor data. That would probably be a fairly big project to implement. This might not be the right way to do it, but it's one idea that comes to mind.

**Comment by BingHan0458** [comment]
Thank you very much! I will try that.
