### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Mealoore** [mit-acl/rl_collision_avoidance#9]
Hello, I want to know how can I watch the result in simulator?  what should I set for?

**Comment by mfe7** [comment]
That should be possible via the config file but will slow down the training quite a bit (the matplotlib visualization is pretty slow).

In Config.py, we load EnvConfig, which comes from [this file](https://github.com/mit-acl/gym-collision-avoidance/blob/release/gym_collision_avoidance/envs/config.py). I think you could add a `self.SHOW_EPISODE_PLOTS = True` somewhere below the line that initializes `EnvConfig` and plots would appear after each episode ends.
